apiVersion: v1
kind: Service
metadata:
    name: node-demo
spec:
    selector:
        app: node-demo
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8090
    type: LoadBalancer
